ALTER TABLE session_summary
    ADD COLUMN IF NOT EXISTS bbox_min_lat DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS bbox_min_lon DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS bbox_max_lat DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS bbox_max_lon DOUBLE PRECISION;
